#!/bin/env bash

. gy_support


if [ ! -e "$R/usr/bin/ssh.org" -o $R/usr/bin/ssh -nt $R/usr/bin/ssh.org ]; then
    if file $(realpath $R/usr/bin/ssh) | grep -q ": ELF"; then
        sudo mv $R/usr/bin/ssh{,.org}
    fi
fi

install winInputBox ssha2
ln -sf $R/usr/bin/{ssha2,ssh}



