#!/bin/env bash

. gy_support


if [ ! -e "$R/usr/bin/ssh.org" -o $R/usr/bin/ssh -nt $R/usr/bin/ssh.org ]; then
    if file $(realpath $R/usr/bin/ssh) | grep -q ": ELF"; then
        sudo mv $R/usr/bin/ssh{,.org}
    fi
fi

install winInputBox ssha2 c /etc/profile.d/ssha2.sh
sudo ln -sf $R/usr/local/bin/ssha2 /usr/bin/ssh
sudo ln -sf $R/usr/local/bin/ssha2 /usr/local/bin/ssh-agent
sudo ln -sf $R/usr/local/bin/ssha2 /usr/local/bin/ssh-add



