#!/usr/bin/env bash

show_stack() {
    local i
    for ((i = 0; i < ${#FUNCNAME[@]}; i++)); do
        printf '#%d %s() at %s:%s\n' \
            "$i" \
            "${FUNCNAME[$i]:-main}" \
            "${BASH_SOURCE[$i]:-}" \
            "${BASH_LINENO[$i - 1]:-0}"
    done
}
show_stack

echo s.install s0 ${BASH_SOURCE[0]}
pwd
echo s.install s1 ${BASH_SOURCE[1]}
echo s.install s2 ${BASH_SOURCE[2]}
echo s.install s3 ${BASH_SOURCE[3]}
echo s.install s4 ${BASH_SOURCE[4]}
echo s.install s5 ${BASH_SOURCE[5]}
echo s.install s6 ${BASH_SOURCE[6]}
echo s.install s7 ${BASH_SOURCE[7]}
. $(dirname $0)/gyi
echo -2
depends yk_support_for_sh
echo -3

install winInputBox ssha2 c
echo -4
install ssha2.sh /usr/local/lib/yk_support_for_sh
install ssha2.sh /usr/local/etc/yk_support_for_sh/shrc.d

echo s.install s05 ${BASH_SOURCE[0]}
echo s.install s15 ${BASH_SOURCE[1]}
echo s.install s25 ${BASH_SOURCE[2]}
echo s.install s35 ${BASH_SOURCE[3]}
echo s.install s45 ${BASH_SOURCE[4]}
echo s.install s55 ${BASH_SOURCE[5]}
echo s.install s65 ${BASH_SOURCE[6]}
echo s.install s75 ${BASH_SOURCE[7]}
echo finished s/install -5




