#!/bin/env ruby


require 'shellwords'
require 'fileutils'
require 'open3'
require  'time'
require 'pty'
require 'io/console'
#$debug = false
#require 'Yk/debug2'
FileUtils.mkdir_p "#{ENV['HOME']}/.local/tmp"
#p > "#{ENV['HOME']}/.local/tmp/ssha.debug_out"
require 'digest'

require 'open3'
require 'io/console'
require 'timeout'



def running_in_wsl?
	File.read("/proc/version").include?("icrosoft") rescue false
end

KEY_CHECK_IN_ADVANCE = ENV["KEY_CHECK_IN_ADVANCE"] == "1"

IN_WSL = running_in_wsl?

SYS_BOOT_TIME = Time.at(`awk '/btime/ {print $2}' /proc/stat`.strip.to_i).to_s.gsub(" ", ".").gsub(":", "-")
PROC_START_CLOCK = IO.read("/proc/#{$$}/stat").split[21].to_i
FPID = "#{PROC_START_CLOCK}.#{Process.pid}"

BY_WIN = IN_WSL
BY_SSH_BAT = ENV["VSCODE_BAT"] == "1"
BY_VSCODE = ENV["VSCODE_NONCE"] && !ENV["VSCODE_NONCE"].empty?
SSH_ORG_PTY = BY_SSH_BAT ? ["/mnt/c/Program Files/Git/usr/bin/winpty.exe", "-Xallow-non-tty", "ssh.exe"] : ["ssh"]
SSH_ORG = BY_SSH_BAT ? "ssh.exe" : "ssh"


SSH_ADD_PTY = BY_SSH_BAT ? ["/mnt/c/Program Files/Git/usr/bin/winpty.exe",  "-Xallow-non-tty", "ssh-add.exe"] : ["ssh-add"]
SSH_ADD = BY_SSH_BAT ? "ssh-add.exe" : "ssh-add"

SSHA_HOME = "#{ENV['HOME']}/.ssha"

#ENV['PATH'] =~ /mnt/c/Users/.*?\/Appdata/ ? VSCODE_BAT = 1 : VSCODE_BAT = 0

WHOMEW = IN_WSL ? `cmd.exe /c 'echo %USERPROFILE%' 2>/dev/null < /dev/null`.chomp : nil
WHOMEL = IN_WSL ? `wslpath '#{WHOMEW}'`.chomp : nil

DEBWF = "#{ENV['HOME']}/.ssha/debug_writer"

def openWriter
	fName = DEBWF
	if !File.exist? fName
		system "mkfifo #{fName}"
	end
	Dir.glob "/proc/*/cmdline" do |cmdline|
		begin
			cmd = IO.read(cmdline).split("\0")
			if cmd == %W{tail -F /home/yougain/.ssha/debug_writer}
				return
			end
		rescue
		end
	end
	system "cd #{WHOMEL}; cmd.exe /c wt wsl -e tail -F #{fName} < /dev/null"
end


openWriter if ENV["DEBUG"]


def aout buff
	IO.write DEBWF, buff.inspect.gsub("\\n", "\\n\n") if ENV["DEBUG"]
end

WSSHA_HOMEL = IN_WSL ? "#{WHOMEL}/.ssha" : nil
LOGD = "#{SSHA_HOME}/logs"
FileUtils.mkdir_p LOGD
TMP_ROOTS = "#{SSHA_HOME}/tmp/boot"
WTMP_ROOTSL = "#{WSSHA_HOMEL}/tmp/boot"
TMP_ROOT = "#{TMP_ROOTS}/#{SYS_BOOT_TIME}"
WTMP_ROOTL = "#{WTMP_ROOTSL}/#{SYS_BOOT_TIME}"
FileUtils.mkdir_p TMP_ROOT
FileUtils.mkdir_p WTMP_ROOTL

FileUtils.chmod 0700, SSHA_HOME



[TMP_ROOTS, WTMP_ROOTSL].each do |root|
	Dir.glob "#{root}/*" do |d|
		if d != root + "/#{SYS_BOOT_TIME}"
			FileUtils.rm_rf d rescue nil
		end
	end
end

TMPD = "#{TMP_ROOT}/ssha-#{FPID}" # TMPD = TMP_ROOT /ssha-$FPID
WTMPDL = "#{WTMP_ROOTL}/ssha-#{FPID}"

FileUtils.mkdir_p TMPD
FileUtils.mkdir_p WTMPDL
WTMPDW = IN_WSL ? (`wslpath -w '#{WTMPDL}' 2>/dev/null`.chomp rescue nil) : nil


SESSION_ID = Process.getsid(0) # 現在のセッションIDを取得
SESSION_START_CLOCK = IO.read("/proc/#{SESSION_ID}/stat").split[21].to_i
FSID = "#{SESSION_START_CLOCK}.#{SESSION_ID}"


VSC_WSL_PORT=41235
VSCODE = `find ~/.vscode-server -name code 2> /dev/null | head -1`.strip


Prog = File.basename($0)
ProgDir= File.dirname(`readlink -f #{$0}`)
begin
require "#{ProgDir}/ask.rb"
require "#{ProgDir}/agent.rb"
rescue Exception => e
	raise
end
require "#{ProgDir}/key.rb"



class Err < StandardError; end



VSC_EDIT_DIR = "#{SSHA_HOME}/vscode_edit" # VSC_EDIT_DIR = SSHA_HOME /vscode_edit
VSC_EDIT_DAEMON_DIR = "#{SSHA_HOME}/vscode_edit_daemons/#{SYS_BOOT_TIME}" # VSC_EDIT_DAEMON_DIR = SSHA_HOME /vscode_edit_daemons / SYS_BOOT_TIME


if false
if BY_VSCODE # vscode's direct child process for remote ssh connection, maybe in WSL
	fork do
		# STDERR.reopen VSC_EDIT_DIR /vscode_edit_daemon.log, "a"
		STDERR.reopen "#{VSC_EDIT_DIR}/vscode_edit_daemon.log", "a"
		FileUtils.mkdir_p VSC_EDIT_DAEMON_DIR rescue nil
		# start = $ cat /proc/$$/stat | awk '{print $22}'
		start = `cat /proc/#{Process.pid}/stat | awk '{print $22}'`.strip
		# vsc_edit_daemon_pipe = VSC_EDIT_DAEMON_DIR / start . Process.pid
		# example # fd = ~/.ssha{!}/data'open-rw
		vsc_edit_daemon_pipe = "#{VSC_EDIT_DAEMON_DIR}/#{start}.#{Process.pid}"
		to_daemon = vsc_edit_daemon_pipe + ".to"
		from_daemon = vsc_edit_daemon_pipe + ".from"
		File.mkfifo to_daemon
		File.mkfifo from_daemon
		END{
		  File.delete to_daemon rescue nil
		  File.delete from_daemon rescue nil
		}
		Thread.new do
		  loop do
			paths = []
			File.open to_daemon do |fr|
			  fr.flock File::LOCK_EX
			  fr.each_line do |ln|
				paths << ln.chomp
			  end
			end
			ret = (Process.ppid != 1 and system VSCODE, *paths) ? "OK" : "ERROR"
			  File.open from_daemon do |fw|
				fw.flock File::LOCK_EX
				fw.write ret + "\n"
			  end
			if Process.pid == 1
			  exit 1
			end
		  end
		end
		#      ents.each do |ent|
		#          File.delete ent rescue nil
		#      end
		#    else
		#      
		#    end
		#end
		loop do
			sleep 300
			if Process.ppid != 1
				begin
					Process.getpgid(Process.ppid)
				rescue Errno::ESRCH
					exit 0
				end
			else
				exit 0
			end
		end
	end
end
end


def sshCommand sshc, cmd = []
	ret = nil
	PTY.spawn "SSH_ASKPASS=\"\" " + [*%W{#{SSH_ORG_PTY.join(' ')} -t}, *sshc, *cmd].shelljoin do |r, w, pid|
		tr, tw = IO.pipe
		t = nil
		mt = Thread.new do
			t = Process.detach pid
			t.join
			tw.write "exit\n"
			tw.flush
		end
		Thread.pass
		line = ""
		loop do
			if pid_exited?(pid)
				break
			end
			ra, = select [r, tr]
			if ra == [tr]
				break
			end
			d = r.readpartial(1024) rescue nil
			if d
				line << d
			end
			lines = line.lines
			i = 0
			lines.each do |l|
				yield l, w
				if !d
					break
				end
				i += 1
			end
			line = ""
		end
		mt.join
		ret = t.value.to_i == 0
	end
	ret
end
		   

def pid_exited?(pid)
	begin
	  # シグナル0を送信してプロセスの存在を確認
	  Process.kill(0, pid)
	  false # プロセスが存在する場合
	rescue Errno::ESRCH
	  true  # プロセスが存在しない場合（終了している）
	rescue Errno::EPERM
	  false # プロセスが存在するがアクセス権がない場合
	end
end

def _clobber dir, num, max
	if File.exist? "#{dir}/#{num}"
		if num < max
			_clobber dir, num + 1, max
			FileUtils.mv "#{dir}/#{num}", "#{dir}/#{num + 1}"
		else
			FileUtils.rm "#{dir}/#{num + 1}"
		end
	end
end

def clobber dir, max
	_clobber dir, 1, max
end

def registerConfig host, user, port, idFile, confPos
	if confPos.empty?
		if File.exist?("#{ENV['HOME']}/.ssh/config")
			FileUtils.cp "#{ENV['HOME']}/.ssh/config", "#{ENV['HOME']}/.ssh/config.bak"
		else
			FileUtils.mkdir_p "#{ENV['HOME']}/.ssh"
			FileUtils.chmod 0700, "#{ENV['HOME']}/.ssh"
			FileUtils.touch "#{ENV['HOME']}/.ssh/config"
		end
		File.open("#{ENV['HOME']}/.ssh/config", "a") do |f|
			f.puts "# Generated by ssha2 at #{Time.now}"
			f.puts "Host #{host}"
			f.puts "    User #{user}"
			f.puts "    Port #{port}"
			f.puts "    IdentityFile #{idFile}" if idFile
			f.puts ""
		end
	else
		file, lno = confPos[0].split ":"
		lno = lno.to_i
		if File.exist? file
			lns = IO.readlines(file)
			s = lno - 1
			prevContent = ["#{File.mtime(file)} #{confPos[0]}\n\n"]
			if lns[s] =~ /\s*Host\s+#{Regexp.escape host}\s*(#|$)/
				prevContent << lns[s]
				last = lns.size
				user_set, port_set, idFile_set = false, false, false
				bind = binding
				mod = false
				found = {}
				same_or_replace = proc do |i, key, value|
					if lns[i] =~ /^(\s*)#{Regexp.escape key}\s+(\S+)(\s*)(#|$)/i
						if $2 != value
							mod = true
							lns[i] = "#{$1}#{key} #{value}#{$3}# Modified from '#{$2}' by ssha2 at #{Time.now}\n"
						end
						found[key] = true
					end
				end
				set_or_insert = proc do |key, value|
					if !found[key]
						lns.insert last, "#{key} #{value} # Inserted by ssha2 at #{Time.now}\n"
						mod = true
					end
				end
				nonBlank = nil
				(s + 1).upto (lns.size - 1) do |i|
					if lns[i] =~ /\s*Host\s+/
						last = nonBlank + 1 || i
						break
					end
					if !lns[i].strip.empty?
						nonBlank = i
					end
					prevContent << lns[i]
					same_or_replace.call i, "User", user
					same_or_replace.call i, "Port" , port
					same_or_replace.call i, "IdentityFile", idFile if idFile
				end
				set_or_insert.call "User", user
				set_or_insert.call "Port", port
				set_or_insert.call "IdentityFile", idFile if idFile
				if mod
					FileUtils.mv file, "#{file}.bak"
					IO.write file, lns.join
					FileUtils.chmod 0600, file
					d = "#{SSHA_HOME}/config_history/#{host}"
					FileUtils.mkdir_p d
					clobber d, 10
					IO.write "#{d}/1", prevContent.join
				end
			else
				userPrompt :msg, "ERROR: cannot register config."
				exit 1
			end
		end
	end
end

def finger2file finger
	
end


def doCheck sshc, dest, modIdFiles, fing2File, pw = nil
	mode = []
	loop do
		rn = rand(10**9..10**10-1)
		buff = ""
		line = ""
		finger = nil
		clearKeysInSSHAgent
		null = open('/dev/null','w')
		system *SSH_ORG , *%W{-O exit}, dest, out: null, err: null
		sshCommand ["-v"] + sshc, %W{echo #{rn}} do |l, w|
			case l
			when /^\r*Enter passphrase for key '(.*?)': /
				finger = nil
				idFile = File.expand_path $1
				if idFile == IdFile && !PassPhrase.empty?
					w.write PassPhrase + "\r\n"
					w.flush
					mode << [idFile, PassPhrase]
				elsif modIdFiles.include? idFile
					passPhrase = userPrompt :passwd, "Enter passphrase for key '#{$1}': "
					w.write passPhrase 
					w.flush
					w.write "\r\n"
					w.flush
					mode << [idFile, passPhrase]
				else
					w.write "\r\n"
					w.flush
				end
			when /'s password: /
				mode << :password
				if !pw
					w.write "\r\n"
					w.flush
				else
					w.write pw + "\r\n"
					w.flush
				end
			when /^#{rn}/
				mode << :success
				if mode[-2].is_a?(Array)
					idFile, passPhrase = mode[-2]
					PassPhrase.replace passPhrase
					IdFile.replace idFile
				else
					idFile = nil
				end
				user, host, port = nil
				confPos = []
				sshCommand ["-G", "-v"] + sshc do |l, w|
					case l
					when /^user /
						user = $'.strip
					when /^host /
						host = $'.strip
					when /^port /
						port = $'.strip
					when /^debug1: (.*?) line (\d+): Applying options for #{Regexp.escape dest}\r*$/
						confPos.push "#{File.expand_path $1}:#{$2}"
					end
				end
				registerConfig host, user, port, idFile, confPos
			when /^\r*Permission denied, please try again.\r*/
				w.write "\r\n"
				w.flush
			when /^debug1: Server accepts key: (.*)/
				finger = $1.strip.split[2]
			when /^Authenticated to .* using "publickey"\./
				if finger # id without passphrase
					mode << [fing2File[finger], ""]
				end
				finger = nil
			when /Connection refused/
				mode << :connection_refused
				userPrompt :msg, l.chomp
			when /No route to host/
				mode << :no_route_to_host
				userPrompt :msg, l.chomp
			when /Are you sure you want to continue connecting/
				yn = userPrompt :yn, l.chomp
				w.write yn + "\r\n"
			when /Please type \'yes\'\, \'no\' or the fingerprint:/
				input = userPrompt :input, l.chomp
				w.write input + "\r\n"
			when /Host key verification failed/
				mode << :host_key_verification_failed
				userPrompt :msg, l.chomp
			end
		end
		if !mode.empty? && mode.all?{ _1 == :password } && !pw
			createAndInstallKey sshc, dest
			redo
		end
		break
	end
	mode
end

def strip_control_chars str
	str.gsub(/\e\[[0-9;]*[a-zA-Z]/, '')  # エスケープシーケンス
	   .gsub(/[\x00-\x08\x0B-\x0C\x0E-\x1F\x7F]/, '')  # 制御文字（\n,\r,\t以外）
end


DebLogF = "#{SSHA_HOME}/logs/ssha2_debug.log"

def debLogF i = 0
	fn = i == 0 ? DebLogF : "#{DebLogF}.#{i}"
	if File.exist?(fn)
		if i != 0 || File.size(fn) > 10 * 1024 * 1024
			fnn = i == 0 ? "#{DebLogF}.1" : "#{DebLogF}.#{i + 1}"
			if i < 9
				FileUtils.mv fn, fnn
				debLogF i + 1
			else
				FileUtils.rm fnn
				FileUtils.mv fn, fnn
			end
		end
	end
end

debLogF

DebLogFD = File.open DebLogF, "a"

def dlog msg
	DebLogFD.puts "#{Time.now.strftime("%Y-%m-%d %H:%M:%S.%L")} ssha2[#{$$}] #{msg}"
	DebLogFD.flush
end

# NUL, SOH, STX, ENQ, ACK, SO, SI, DLE, DC4, EM, GS, RS, US : ttyで一般的に使われない制御コード（強調対象）
TTY_UNUSED_CONTROL_BYTES = [0x00, 0x01, 0x02, 0x05, 0x06, 0x0E, 0x0F, 0x10, 0x14, 0x19, 0x1D, 0x1E, 0x1F].freeze

CTRL_ESCAPE_BG_YELLOW = "\e[43m"
CTRL_ESCAPE_FG_RED = "\e[31m"
CTRL_ESCAPE_FG_GREEN = "\e[32m"
CTRL_ESCAPE_RESET = "\e[0m"

def escapedByte(byte, fg)
	"#{CTRL_ESCAPE_BG_YELLOW}#{fg}<0x%02x>#{CTRL_ESCAPE_RESET}" % byte
end

# ASCII-8BIT文字列をUTF-8へ変換し、invalid/undefなバイト列は赤字/黄背景、
# ttyで一般的に使われない制御コードは緑字/黄背景で1バイトずつ<0xff>形式に強調する
def binaryToDisplayUtf8(bin)
	utf8 = bin.dup.force_encoding("UTF-8")
	scrubbed = utf8.scrub { |bytes|
		bytes.each_byte.map { |b| escapedByte(b, CTRL_ESCAPE_FG_RED) }.join
	}
	scrubbed.gsub(/[\x00-\x1f]/) { |c|
		TTY_UNUSED_CONTROL_BYTES.include?(c.ord) ? escapedByte(c.ord, CTRL_ESCAPE_FG_GREEN) : c
	}
end

	def split_completed_and_pending!(buf)
	  return [nil, buf] if buf.empty?

	  i = buf.bytesize - 1
	  cont = 0

	  while i >= 0 && (buf.getbyte(i) & 0b11000000) == 0b10000000
	    cont += 1
	    i -= 1
	  end

	  return [buf, nil] if cont == 0

	  lead = buf.getbyte(i)
	  need = case lead
	         when 0xC2..0xDF then 1
	         when 0xE0..0xEF then 2
	         when 0xF0..0xF4 then 3
	         else 0
	         end

	  if need > 0 && cont < need
	    pending_start = i + 1
	    completed = buf.byteslice(0, pending_start)
	    pending = buf.byteslice(pending_start, buf.bytesize - pending_start)

	    buf.replace(pending)
	    return [completed, pending]
	  end

	  [buf, nil]
	end




def genIOFiberCode code, cls
	%W{r w e}.each do |prefix|
		c = code.clone
		c.gsub! "io", prefix + "io"
		c.gsub! "IO", prefix.capitalize + "IO"
		c.gsub! "fiber", prefix + "fiber"
		c.gsub! "Fiber", prefix.capitalize + "Fiber"
		cls.class_eval c
	end
end

def insert_by array, item, &key
 	index = array.bsearch_index { |element| key.call(element) >= key.call(item) }
 	array.insert(index || array.length, item)
end

def sampleFromArrays *arrs
	alls = 0
	arrs.each do |a|
		alls += a.size
	end
	ord = rand 0 ... alls
	asz = 0
	arrs.each do |a|
		if ord < (asz += a.size)
			return a, a[asz - ord - 1]
		end
	end
end


class Fiber
	attr_reader :io, :mode
	def setIO io, mode
		if @io
			raise "#{self.inspect} is already waiting an IO, #{@io.inspect}"
		else
			@io = io
			@mode = mode
			case mode
			when :read
				SelectRIOList[io] = true
				@io._setRFiber self
			when :write
				SelectWIOList[io] = true
				@io._setWFiber self
			when :error
				SelectEIOList[io] = true
				@io._setEFiber self
			end
		end
	end
	def resetIO
		case @mode
		when :read
			SelectRIOList.delete @io
			@io._resetRFiber
		when :write
			SelectWIOList.delete @io
			@io._resetWFiber
		when :error
			SelectEIOList.delete @io
			@io._resetEFiber
		end
		@io = @mode = nil
	end
#	genIOFiberCode ioCode, self
	attr_reader :timeout
	def timeout_sec
		to_sec = @timeout - Time.now
		if to_sec < 0
			to_sec = 0
		end
		to_sec
	end
	
	@@FibersWithTimeout = []
	def setTimeout t # Time object
		@timeout = t
		insert_by(@@FibersWithTimeout, self) do |item|
			item.timeout
		end
	end
	def resetTimeout
		@timeout = nil
		@@FibersWithTimeout.each_with_index do |item, i|
			if item == self
				@@FibersWithTimeout.delete_at i
			end
		end
	end
	def self.timeout_sec
		@@FibersWithTimeout[0]&.timeout_sec
	end
	def self.timeoutList
		topTimeout = @@FibersWithTimeout[0]&.timeout
		if topTimeout
			ret = []
			@@FibersWithTimeout.each do |fib|
				if fib.timeout == topTimeout
					ret.push fib if !ret.include?(fib)
				else
					break
				end
			end
			ret
		else
			nil
		end
	end
	def self.cont fiber, exception = nil # in SelectFiber
		params = fiber.resume exception # dispatch!
		if params.is_a? Array
			tindex = params.find_index{|item| item&.is_a?(Time)}
			if tindex
				tout = params[tindex] rescue nil
				params.delete_at(tindex)
			else
				tindex = params.find_index{|item| item.nil?}
				params.delete_at(tindex) if tindex
			end
		end
		if tout
			fiber.setTimeout tout
		end
		if !params.empty?
			case params
			in :finish
			in :nest
			in IO => io, :read | :write | :error => mode
				fiber.setIO io, mode
			end
		end
	end

	SelectFiber = Fiber.new do
		begin
			loop do
				exception = nil
				tout = Fiber.timeout_sec
				tout_fibers = Fiber.timeoutList
				mayRaise = false
				re = IO::IOWithReadException.keys & SelectRIOList.keys
				we = IO::IOWithWriteException.keys & SelectWIOList.keys
				ee = IO::IOWithErrorException.keys & SelectEIOList.keys
				if [re, we, ee].any?{!_1.empty?}
					mayRaise = true
					if !tout || tout != 0
						tout = 0
						tout_fibers = []
					end
				end
				if SelectRIOList.empty? && (!tout_fibers || tout_fibers&.empty?) && SelectWIOList.empty? && SelectEIOList.empty?
					break
				end
				all = nil
				ord = nil
				rios = []
				fiber = nil
				arrived = nil
				begin
					rios, wios, eios = IO.select SelectRIOList.keys, SelectWIOList.keys, SelectEIOList.keys, tout
					if !rios
						if mayRaise
							arr, io = sampleFromArrays re, we, ee
							case arr
							when re
								exception = IO::IOWithReadException.delete(io)
								fiber = io.rfiber
							when we
								exception = IO::IOWithWriteException.delete(io)
								fiber = io.wfiber
							when ee
								exception = IO::IOWithErrorException.delete(io)
								fiber = io.efiber
							end
						else
							fiber = tout_fibers.sample
							exception = Timeout::Error
						end
					else
						all = rios + wios + eios
						arr, io = sampleFromArrays rios, wios, eios
						case arr
						when rios
							fiber = io.rfiber
						when wios
							fiber = io.wfiber
						when eios
							fiber = io.efiber
						end
					end
				ensure
					fiber&.resetIO
					fiber&.resetTimeout
				end
				cont fiber, exception
			end
		rescue Exception => e
			STDERR.puts e.full_message(highlight: false, order: :top)
			exit 1
		end		
	end
	MainFiber = Fiber.current

	def digest_call_info arg1 = nil, arg2 = nil
		lbl = Proc.new do |l|
			if l =~ /\<class:(.*)\>/
				$1
			else
				l
			end
		end
		case [arg1, arg2]
		in Array => ciarr, nil
			ord = 0
		in Integer => ord, nil
			ciarr = caller_locations
		in Array => ciarr, Integer => ord
		in Integer => ord, Array => ciarr
		end
		ciarr.reject!{|item| item.path == "<internal:kernel>"}
		orgPath = ciarr[0].path
		orgLno = ciarr[0].lineno
		orgLabel = ciarr[0].base_label
		str = ciarr[ord + 1..-1].reduce "#{orgPath.basename}:#{lbl.call orgLabel}:#{orgLno}" do |str, ci|
			s = []
			if orgPath != ci.path
				s.push File.basename(ci)
			end
			if orgLabel != ci.base_label
				s.push lbl.call(ci.base_label)
			end
			if orgLno != ci.lineno
				s.push ci.lineno.to_s
			end
			if !s.empty?
				str + ";" + s.join(":")
			else
				str
			end
		end
		str
	end

	OrgCI = Struct.new(:path, :base_label, :lineno)
	def set_fork_info
		oi = org_inspect
		if oi =~ /(\/.*):(\d+)/
			origin = OrgCI.new($1, caller_locations(1)[0].base_label, $2.to_i)
		end
		@fork_info = caller_locations(2)
		@fork_info.unshift origin
	end

	alias_method :org_inspect, :inspect

	def prop_inspects
		ia = instance_variables
		ia.delete("@fork_info".intern)
		m = ia.map do |name|
			"#{name}=#{instance_variable_get(name).inspect}"
		end
		ms = m.join(", ")
		if !ms.empty?
			" " + ms
		else
			""
		end
	end

	def inspect
		oi = org_inspect
		if oi =~ /(\/.*):(\d+)/
			oi = $` + digest_call_info(@fork_info) + prop_inspects + $'
		end
		oi
	end

	def self.fork
		f = Fiber.new do
			begin
				yield
			rescue Exception => e
				STDERR.puts e.full_message(highlight: false, order: :top)
  				exit 1
			end
			:finish
		end
		f.set_fork_info
		cont f
	end
	def self.pararell
		yield
#		loop do
			if Fiber.current == MainFiber
				SelectFiber.resume
			else
				Fiber.yield :nest
			end
#		end
	end

	class Unexpected < Exception
	end

	def self.wait *args
		ret = Fiber.yield *args # may return Exception
		case ret
		when Exception
			raise ret
		when nil
		else
			raise ArgumentError.new "unknown result"
		end
		ret
	end

	def self.sleep n
		if n > 0
			Fiber.yield Time.now + n
		end
	end



end


Prefix2Mode = { "r" => "read", "w" => "write", "e" => "error" }


def genFiberCode code, cls
	%W{r w e}.each do |prefix|
		c = code.clone
		c.gsub! "fiber", prefix + "fiber"
		c.gsub! "Fiber", prefix.capitalize + "Fiber"
		cls.class_eval c
	end
end

SelectRIOList = Hash.new
SelectWIOList = Hash.new
SelectEIOList = Hash.new


class IO
	fiberCode = %{
		attr_reader :fiber
		def _setFiber fiber
			@fiber = fiber
		end
		def _resetFiber
			@fiber = nil		
		end
	}
	genFiberCode fiberCode, self

	IOWithReadException = {}
	IOWithWriteException = {}
	IOWithErrorException = {}

	def getCompleted
		@buff ||= "".b # ASCII-8bit
	 	return nil if @buff.empty?

	  i = @buff.bytesize - 1
	  cont = 0

	  	while i >= 0 && (@buff.getbyte(i) & 0b11000000) == 0b10000000
	   	cont += 1
	   	i -= 1
	  	end
		if cont == 0
			ret = @buff
			@buff = "".b
	 		return ret
		end

		lead = @buff.getbyte(i)
		need = 	case lead
	         	when 0xC2..0xDF then 1
	         	when 0xE0..0xEF then 2
	         	when 0xF0..0xF4 then 3
	         	else 0
	         	end

		if need > 0 && cont < need
			pending_start = i + 1
			completed = buf.byteslice(0, pending_start)
			pending = buf.byteslice(pending_start, buf.bytesize - pending_start)
			@buff.replace(pending)
	   	return completed
		end

		ret = @buff
		@buff = "".b
 		return ret
	end

	def f_getTTYStr t = nil
		@buff ||= "".b # ASCII-8bit
		if t
			tout = Time.now + t
		end
		loop do
			if !@buff.empty?
				if Encoding.default_external == Encoding::UTF_8
					completed = getCompleted
					if completed
						return binaryToDisplayUtf8(completed)
					end
				else
					begin
						dst = +""
						@@conv.primitive_convert(@buff, dst)
						if !dst.empty?
							return dst
						end
					rescue Encoding::InvalidByteSequenceError
						ret = @buff.encode(Encoding.default_external, "ASCII-8BIT", invalid: :replace, undef: :replace, replace: "?")
						@buff.clear
						return ret
					end
				end
			end
			Fiber.wait(self, :read, tout)
			begin
				@buff += readpartial 1024
			rescue Errno::EIO
				if tty?
					raise EOFError.new
				else
					raise
				end
			end
		end
	end

	def f_getTTYLine t = nil
		f_expectTTYStr "\n", t = nil
	end

	def f_expectTTYStr expr, t = nil
		@buff ||= "".b # ASCII-8bit
		if t
			tout = Time.now + t
		end
		loop do
			case expr
			when String
				fe = expr.force_encoding("ASCII-8BIT")
				exprPos = @buff.index fe
				if exprPos
					untilExpr = @buff.slice! 0...(exprPos + fe.size)
					return binaryToDisplayUtf8(untilExpr)
				end
			when Regexp
				bm = @buff.force_encoding(expr.to_s.encoding)
				if bm =~ expr
					bm.replace($')
					@buff.replace(bm.b)
					return binaryToDisplayUtf8($` + $&)
				end
			end
			tmp = Fiber.wait(self, :read, tout)
			if tmp.is_a? Exception
				raise tmp
			end
				@buff += readpartial 1024
			#else
			#	p.blue
			#end
		end
	end

	def readable?
	  mode = io.fcntl(Fcntl::F_GETFL) & Fcntl::O_ACCMODE
	  mode == Fcntl::O_RDONLY || mode == Fcntl::O_RDWR
	end

	def writable?
	  mode = io.fcntl(Fcntl::F_GETFL) & Fcntl::O_ACCMODE
	  mode == Fcntl::O_WRONLY || mode == Fcntl::O_RDWR
	end

	attr_reader :read_exception, :write_exception, :error_exception

	def set_exception e, mode # raise exception when no data arrived
		case mode
		when :read
			IOWithReadException[self] = e
		when :write
			IOWithWtiteException[self] = e
		when :error
			IOWithErrorException[self] = e
		else
			raise ArgumentError.new("cannot determine readable or writable")
		end
	end

end


def do_ssh *args
	verbose = true if args.include? "-v"
	if KEY_CHECK_IN_ADVANCE
		exec *args
	else
		#ENV.delete 'SSH_ASKPASS'
		wsz = STDIN.winsize
		shellID = "#{FPID}.#{rand(10000000000).to_s}"
		args.pop # remove temporary shell for KEY_CHECK_IN_ADVANCE=1
		args.push "SHELL_ID=#{shellID} WINSZ=#{wsz.join(",")} bash --rcfile "' <(echo "source ~/.bashrc; PS1=\"[MyRemotePrompt]\$ \"")'
		case args[0]
		when "ssh"
		when "ssh.exe"
			args.unshift "-Xallow-non-tty"
			args.unshift "/mnt/c/Program Files/Git/usr/bin/winpty.exe"
		end
		if !verbose
			args.insert 1, "-v"
		end
		pid = nil
		wsz = STDIN.winsize
		slv = nil
		trap :WINCH do
			begin
				new_wsz = STDIN.winsize
				if new_wsz != wsz
					wsz = new_wsz
					if pid
						begin
							if slv && !slv.closed?
								slv.winsize = wsz
								Process.kill :WINCH, pid if pid
							end
						rescue Errno::ESRCH
						end
					end
				end
			rescue
			end
		end
		eoutLog = File.open "#{SSHA_HOME}/logs/ssha2_eout.log", "a"
		PTY.open do |master, slave|
			slv = slave
			master.sync = true
			slave.sync = true
			slave.winsize = wsz
			#ENV['SSH_ASKPASS'] = ""
			er, ew = IO.pipe
			pid = fork do
				master.close
				er.close
				STDOUT.reopen slave
				STDIN.reopen slave
				STDERR.reopen ew
				slave.close
				3.upto(1023) do |fd|
					IO.for_fd(fd).close rescue nil
				end
				exec *args
			end
			ew.close
			begin
				#STDERR.reopen slave, "w"
				slave.close
				begin
					vport = nil
					Fiber.pararell do
						Fiber.fork do
							allocPortLine = nil
							loop do
								begin
									line = er.f_getTTYLine
								rescue EOFError => e
									STDIN.set_exception EOFError.new, :read
									break
								end
								dlog "err_out: #{line.inspect}"
								if verbose
									line.gsub!(/Error:.*\n|^.*disabled port forwarding/i) { "\e[31m#{$&}\e[0m" }
									STDERR.write line
									STDERR.flush
								else
									if line !~ /^debug\d+: / && line != allocPortLine
										STDERR.write line
									end
								end
								if !vport && line =~ /Allocated port (\d+) for remote forward to 127.0.0.1:\d+/
									vport = $1
									allocPortLine = line
								end
							end
						end
						Fiber.fork do
							begin
								data = master.f_expectTTYStr "]$"
							rescue EOFError, Errno::EIO
							end
							if data
								aout data
								# if !cmded && strip_control_chars(residue) =~ /\]\$/ # command prompt
								pre_scr = <<~END
									export SYS_START=$(awk '/btime/ {print $2}' /proc/stat)
									export SSH_VSCODE_PORT=#{vport}
									mkdir -p /tmp/vscode-ssh-ports/$(awk '/btime/ {print $2}' /proc/stat)
									str="`grep SHELL_ID=#{shellID} /proc/*/environ 2>&1| grep match | awk -F'/' '{print $3}'`"
									for s in $str; do
										if [ -r /proc/$s/stat ] && [ $s != self ]; then
											echo s=$s
											sppid="$(awk '{print $4}' /proc/$s/stat 2>&1)"
											echo sppid=$sppid
											if [ -n "$sppid" ]; then
												read cl < /proc/$sppid/cmdline
												echo cl =$cl
												if [[ $cl == "sshd-session:"* ]] || [[ $cl == "sshd:"* ]]; then
													spid=$s
													st=$(awk '{print $22}' /proc/$sppid/stat)
													echo #{vport} > /tmp/vscode-ssh-ports/$SYS_START/$st.$sppid
												fi
											fi
										fi
									done
								END
								pre_scr.each_line do |ln|
									ln.lstrip!
									master.write ln
								end
								pre_scr = <<~END
									for d in /tmp/vscode-ssh-ports/*; do
										if [ "$(basename $d)" != "$SYS_START" ]; then
											rm -rf $d
										fi
									done
								END
								pre_scr.each_line do |ln|
									ln.lstrip!
									master.write ln
								end
								pre_scr = <<~END
									for ent in /tmp/vscode-ssh-ports/$SYS_START/*; do
										if [ $ent != /tmp/vscode-ssh-ports/$SYS_START/* ];then
											tmp=$(basename $ent)
											if ! kill -s 0 ${tmp#*.} 2>&1; then
												rm -f $ent
											fi
										fi
									done
								END
								pre_scr.each_line do |ln|
									ln.lstrip!
									master.write ln
								end
								pre_scr = <<~END
									while IFS= read -r var; do
										if [[ $var == SSH* ]]; then
											export "$var"
										fi
									done < <(tr '\\0' '\\n' < /proc/$spid/environ)
								END
								pre_scr.each_line do |ln|
									ln.lstrip!
									master.write ln
								end
								pre_scr = <<~END
									sdafsadfsadf; exec `getent passwd "$USER" | cut -d: -f7`
								END
								pre_scr.each_line do |ln|
									ln.lstrip!
									master.write ln
								end
								data = master.f_expectTTYStr "sdafsadfsadf: command not found"
								aout data
								Fiber.pararell do
									Fiber.fork do
										STDIN.raw!
										loop do
											begin
												d1 = STDIN.f_getTTYStr
											rescue EOFError
												break
											end
											master.write d1
											master.flush
										end
									end
									Fiber.fork do
										loop do
											begin
												d2 = master.f_getTTYStr
											rescue EOFError
												er.set_exception EOFError.new, :read
												break
											end
											STDOUT.write d2
											STDOUT.flush
										end
									end
								end
							end
						end
					end
				ensure
					STDIN.cooked!
				end
			ensure
				Process.waitpid pid
			end
		end
	end
end

if BY_WIN
	if ! File.exist?("/mnt/c/Program Files/Git/usr/bin/winpty.exe")
		userPrompt :msg, "ERROR: '/mnt/c/Program Files/Git/usr/bin/winpty.exe', not found. please install Git for Windows."
		exit 1
	end
end




check = false

def clause
	yield
end

def main
	optArgs = {}
	clause do
		case ARGV[0]
		when "--ssh-agent"
			ARGV.shift
			while !ARGV.empty?
				case ARGV[0]
				when "--"
					ARGV.shift
					break
				when /^\-([^\s]*)/
					$1.each_char do |c|
						if "aEOPt".include?(c)
							optArgs[c] = $' != "" ? $' : ARGV.shift
							break
						else
							optArgs[c] ||= 0
							optArgs[c] += 1
						end
					end
					ARGV.shift
				else
					break
				end
			end
			cmdline = ARGV
			if optArgs["k"] && cmdline.empty?
				destroySSHAgent
				exit 0
			end
			if optArgs.empty? && cmdline.empty?
				displaySSHAgentParams
				exit 0
			end
			STDERR.puts "ERROR: unsupported options/commands.\n       This is a modified ssh-agent. Please use '/usr/bin/ssh-agent ...'."
			exit 1
		when "--ssh-add"
			ARGV.shift
			getKeyListInSSHAgent
			exec "/usr/bin/ssh-add", *ARGV
		when "--ask"
			ARGV.shift
			res = userPrompt :passwd, ARGV[0]
			puts res
			exit 0
		when "--print_tmp_script_file_name"
			print_tmp_script_file_name = true
			ARGV.shift
			redo
		when "--server"
			require "#{ProgDir}/proot_server.rb"
			proot_server            
		when "--check"
			ARGV.shift
			check = true
			redo
		else
			nextIsOptArg = false
			dest = nil
			cmdarr = []
			cmdpos = nil
			terminal = false
			inserter = %W{proot-distro login ubuntu --bind /dev/null:/etc/mtab -- su #{ENV['USER']} -c}
			curOpt = nil
			optArg = Hash.new{|h, k| h[k] = []}
			optLine = []
			optFin = false
			subsys = false

			u = `#{SSH_ORG} 2>&1 < /dev/null` # for Windows ssh.exe initial setup
			aOpts = ""
			if u =~ /\[\-(\w\w+)\]/
				sOpts = $1
			end
			while u =~ /\[\-(\w) /
				aOpts += $1
				u = $'
			end

			ARGV.each_with_index do |arg, i|
				if cmdarr.empty?
				if !optFin
					if nextIsOptArg
						nextIsOptArg = false
						optArg[curOpt].push arg
						optLine.push "-#{curOpt}", arg
						next
					end
					# 先頭が-の引数はオプション引数とみなす
					if arg == "--"
						optFin = true
						next
					elsif arg =~ /^\-/
						curOpt = nil
						$'.each_char do |c|
							if curOpt.nil?
								case c
								when "s"
									subsys = true
								when "t"
									terminal = true
								when "T"
									terminal = false
								when /^[#{sOpts}]$/
									optLine.push "-#{c}"
								when /^[#{aOpts}]$/
									optArg[curOpt = $&].push ""
								end
							else
								optArg[curOpt][-1] += c
							end
						end
						if curOpt
							if optArg[curOpt][-1] == ""
								nextIsOptArg = true
							else
								optLine.push "-#{curOpt}", optArg[curOpt][-1]
							end
						end
						next
					end
				end
				if !dest
					dest = arg
				else
					cmdpos = i
					cmdarr << arg        
				end
				else
					cmdarr << arg
				end
			end

			if !cmdpos
				optLine <<  "-t"
				cmdarr = []
				terminal = true
			end
			sshc = optLine + ["--", dest]

			user = nil
			host = nil
			port = nil
			hostname = nil
			idFileList = []
			
			paramLines = []
			IO.popen "echo 1 |SSH_ASKPASS=\"\" " + [*%W{ssh -G}, *sshc].shelljoin + " 2>&1 </dev/null" do |io|
				io.each_line do |line|
					case line
					when /^user /
						user = $'.strip
					when /^host /
						host = $'.strip
					when /^hostname/
						hostname = $'.strip
					when /^port /
						port = $'.strip
					when /^identityfile /
						idFileList.push File.expand_path($'.strip)
					end
					paramLines << line
				end
			end
			paramLines.reject!{ _1 =~ /^\w+algorithms / || _1 =~ /^Pseudo\-terminal/ }

			idFileFingList = {} 
			idFileFingToFileName = {}
			idFileList.each do |idf|
				if File.exist? idf
					fing = getFing(idf)
					idFileFingList[idf] = fing
				end                
			end
			id_files_content = ""
			fing2File = {}
			idFileFingList.each do |idf, fing|
				id_files_content << "#{fing} #{idf}\n"
				fing2File[fing] ||= idf
			end
			prev_id_files_content = IO.read "#{SSHA_HOME}/id_files" rescue ""
			if check
				testFiles = idFileList
			elsif prev_id_files_content != id_files_content
				#p prev_id_files_content
				#p id_files_content
				prev_a = []
				prev_id_files_content.each_line do |line|
					if line =~ /\#/
						line = $`
					end
					prev_a << line.strip.split(" ", 2).values_at(1, 0)
				end
				modifiedFiles = []
				(idFileFingList.to_a - prev_a).each do |idf, fing|
					modifiedFiles.push idf
				end
				testFiles = modifiedFiles
			else
				testFiles = []
			end
			if !testFiles.empty?
				if (resc = doCheck(sshc, dest, testFiles, fing2File)[-1]) == :success
					IO.write "#{SSHA_HOME}/id_files", id_files_content
				end
			end
			
			if !user
				userPrompt :msg, paramLines.join
				exit 1
			end

			if SSH_ORG == "ssh.exe"

				IO.write "#{WTMPDL}/config", paramLines.join
				loop do
					badLines = []
					fcnt = 0
					IO.popen "cd #{WTMPDL};ssh.exe -G -F config #{dest} 2>&1 </dev/null" do |fr|
						fr.each_line do |ln|
							ln.chomp!
							if ln =~ /: line (\d+): Bad /
								badLines.push $1.to_i
							end
						end
					end
					j = 0
					if badLines.empty?
						break
					end
					File.open "#{WTMPDL}/config", "w" do |fw|
						paramLines.each_with_index do |ln, i|
							if i + 1 == badLines[j]
								# remove bad lines
								j = j + 1
								next
							end
							if ln !~ /\# replaced by ssha2/ && ln =~ /^(\w+)file /
								files = $'.split
								pre = $1 + "file "
								# copy under windows userprofile and replace file parameter on config file
								wfiles = []
								files.each do |fi|
									fi = File.expand_path fi
									if File.exist? fi
										fcnt += 1
										FileUtils.cp fi, WTMPDL + "/file." + fcnt.to_s
										wfiles.push WTMPDW + "\\file." + fcnt.to_s
									end
								end
								if !wfiles.empty?
									ln = pre + wfiles.join(" ") + " # replaced by ssha2"
								else
									next
								end
							end
							fw.write ln
						end
					end
				end
			end
			# setting ENV for ssh-add
			added = getKeyListInSSHAgent

			if KEY_CHECK_IN_ADVANCE
				res = catch :key_available do
					idFileList.each do |idf|
						if File.exist? idf
							if key_has_passphrase? idf
								finger = getFing idf
								if !added.include? finger
									errExit = proc do
										userPrompt :msg, "ERROR: #{idf} not added to ssh-agent\nPlease add it with ssh-add #{idf}"
										exit 1
									end
									if PassPhrase.empty?
										phrase = userPrompt :passwd, "Input passphrase for #{idf}: "
										if ssh_add idf, phrase
											PassPhrase.replace phrase
											IdFile.replace idf
										else
											errExit.call
										end
									elsif idf == IdFile
										ssh_add idf, PassPhrase or errExit.call
										IdFile.replace idf
									end
								end
							end
							throw :key_available, :key_available
						end
					end
				end 
				res == :key_available or (
					if !check
						check = true
						redo
					end
					userPrompt :msg, "ERROR: no key available"
					exit 1
				)
			end

			#if IN_WSL && !`which winInputBox 2> /dev/null`.strip.empty?
			#    ENV['SSH_ASKPASS'] = `which winInputBox 2> /dev/null`.strip
			#end

			logit = proc do |msg|
				File.open "#{SSHA_HOME}/cmd_log", "a" do |f|
					f.write "ssh[#{$$}] #{Time.now.strftime("%Y-%m-%d %H:%M:%S.%L")} #{msg}\n"
				end
			end
			if ENV['SSHA_CMD_LOG']
				logit.call "started: ssh #{ARGV.join(" ")}"
			end
			info_d = "#{SSHA_HOME}/limited_controlled_hosts/#{dest}:#{port}"
			limit = IO.read("#{info_d}/limit").to_i rescue nil
			prev = IO.read("#{info_d}/.prev_trial").to_i rescue 0
			r, w = nil
			if limit
				btime = `grep btime /proc/stat`.split[1]
				proc_unique = "#{btime}/#{File.read("/proc/#{$$}/stat").split[21].to_i}-#{$$}"
				info_d_each = "#{info_d}/#{proc_unique}"
				FileUtils.mkdir_p info_d_each
				if (Time.now.to_i - prev) > limit
					closeControlCMD = "#{SSH_ORG} -O exit #{port && "-p #{port}"} #{dest}"
					system "#{closeControlCMD} > /dev/null 2>/dev/null"
					logit.call closeControlCMD
				end
				IO.write "#{info_d}/.prev_trial", Time.now.to_i

				if ENV['SSHA_CMD_LOG']
					this_pid = $$
					pstart = File.read("/proc/#{$$}/stat").split[21].to_i rescue (p; exit(0))
					fork do
						prev_sc = nil
						logF = File.open "#{info_d_each}/syscall_log", "a"
						ausycallExist = File.exist? "/usr/bin/ausycall"
						sc_time = nil
						slist = {}
						loop do
							sc = IO.read "/proc/#{this_pid}/syscall" rescue (p; exit(0))
							if pstart != (File.read("/proc/#{this_pid}/stat").split[21].to_i rescue (p; exit(0)))
								exit 0
							end
							if sc != prev_sc
								sc_time = Time.now
								FileUtils.rm_f "#{info_d_each}/stalled"
								scnum = sc.split[0].to_i
								slist[scnum] ||= " " + `ausyscall #{scnum}`.chomp
								scname = slist[scnum]
								msg = "#{sc_time.strftime("%Y-%m-%d %H:%M:%S.%L")} ssh[#{this_pid}]#{scname} #{sc}"
								logF.puts msg
								logF.flush
							else
								if !File.exist? "#{info_d_each}/stalled"
									FileUtils.touch "#{info_d_each}/stalled" 
									File.utime(sc_time, sc_time, "#{info_d_each}/stalled")
								end
							end
							prev_sc = sc
							sleep 0.1
						end
					end
				end
			end
			if dest && File.exist?("#{ENV['HOME']}/.sshu/hosts/#{dest}")
				exec "ssh", *sshc, "ssha2", "--server", user, *cmdarr
			else
				if cmdarr.empty?
					if IN_WSL
						vport = VSC_WSL_PORT
						r, w = IO.pipe
						pid = fork do
							require 'socket'
							r.close
							server = TCPServer.new(VSC_WSL_PORT) rescue exit(1)
							puts "VSCode Control Server listening on port #{VSC_WSL_PORT}"
							Process.daemon
							w.puts "started"
							w.flush
							w.close

							loop do
								# クライアントからの接続を待つ
								client = server.accept
								
								# 各クライアントを別スレッドで処理
								Thread.new(client) do |conn|
									begin
										puts "Client connected: #{conn.peeraddr[3]}"
										
										# データを受信
										while line = conn.gets
											puts "Received: #{line.chomp}"
											line.chomp!
											case line
											when /^test$/
												conn.puts "OK"
											when /^open remote\s+([\w\-]+)$/
												# エコーバック
												host = $1
												conn.puts "Echo: #{line}"
												system "code --remote ssh-remote+#{host} &"
											end
										end
									rescue => e
										puts "Error: #{e.message}"
									ensure
										conn.close
										puts "Client disconnected"
									end
								end
							end
						end
						w.close
						Process.wait pid
						ret = r.readpartial(1024) rescue nil
						if ret
							if ret.chomp == "started"
								r.close
							else
								STDERR.puts "ERROR: detected abnormal debug monitor."
								exit 1
							end
						end
					else
						vport = 0
						# vport = ENV['VS_CONTROL_PORT']:if.to_i
						if ENV['VS_CONTROL_PORT']
							vport = ENV['VS_CONTROL_PORT'].to_i
						elsif File.exist? "/tmp/vscode_control"
							ent = Dir.entries("/tmp/vscode_control/sshds").delete_if{ |e| e == "." || e == ".." || e != SYS_START }[0]
							entst = {}
							Dir.entries("/tmp/vscode_control/sshds/#{ent}").each do |ent|
								next if ent !~ /^\d+\.\d+$/
								sproc_start, spid = ent.split(".")
								entf = "/tmp/vscode_control/sshds/#{SYS_START}/#{ent}"
								t = IO.read("/proc/#{spid}/stat").split[21].to_i rescue 0
								if t == sproc_start.to_i
									#FileUtils.rm_f entf rescue nil
									entst[entf] = t
								end
							end
							if !entst.empty?
								vport = catch :found do
									entst.keys.sort_by{ |entf| entst[entf] }.reverse_each do |entf|
										v = IO.read entf rescue 0
										require 'socket'
										TCPSocket.open("127.0.0.1", v.to_i) do |s|
											s.write "test\n"
											resp = s.gets.chomp rescue nil
											if resp == "OK"
												throw :found, v.to_i
											end
										end
									end
								end
							end
						end
					end
					free_port = "0"
					if KEY_CHECK_IN_ADVANCE
						rand_id = (10**9 + rand(9*10**9)).to_s
						io = IO.popen [*SSH_ORG, "-q", *sshc, "bash"], "w+"
						begin
							io.write('
								find_free_port() {
									local port=$((10000 + RANDOM % 55535))
									while (echo >/dev/tcp/127.0.0.1/$port) 2>/dev/null; do
										port=$((10000 + RANDOM % 55535))
									done
									echo $port
								}

								FREE_PORT=$(find_free_port)
								echo $FREE_PORT
								mkdir -p /tmp/vscode_control/shell_wrappers
								cat <<END > /tmp/vscode_control/shell_wrappers/'"#{rand_id}"'.ssha_set_vsc_port.sh
		#!/bin/bash

		find_sshd_parent() {
		local pid=\$\$
		
		while [ \$pid -gt 1 ]; do
			# プロセス名を取得
			local proc_name=\$(cat /proc/\$pid/comm 2>/dev/null)
			
			# sshdかチェック
			if [[ "\$proc_name" == "sshd" ]]; then
			echo \$pid
			return 0
			fi
			
			# 親プロセスIDを取得
			pid=\$(awk '"'"'{print \$4}'"'"' /proc/\$pid/stat 2>/dev/null)
			
			if [ -z "\$pid" ]; then
			return 1
			fi
		done
		
		return 1
		}


		export VSCODE_CONTROL_PORT=$FREE_PORT
		SSHD_PID=\$(find_sshd_parent)
		if [ -n "\$SSHD_PID" ]; then
			INFO_DIR=/tmp/vscode_control/sshds/\$(awk '"'"'/btime/ {print \$2}'"'"' /proc/stat)
			mkdir -p \$INFO_DIR
			echo $FREE_PORT > \$INFO_DIR/\$(cat /proc/\$SSHD_PID/stat | awk '"'"'{print \$22}'"'"').\$SSHD_PID
		fi

		exec $(getent passwd $USER | cut -d: -f7)            
		END
								chmod +x /tmp/vscode_control/shell_wrappers/'"#{rand_id}"'.ssha_set_vsc_port.sh
							')
							io.close_write
						ensure
							free_port = io.read.chomp
							io.close
						end
					end
					if vport != 0
						if print_tmp_script_file_name
							proxyBat = "#{WTMPDL}/ssh_proxy.bat"
							IO.write proxyBat, <<~END
								@echo off
								set SSH_ASKPASS=c:\\Program Files\\Git\\mingw64\\bin\\git-askpass.exe
								set SSH_ASKPASS_REQUIRE=force
								ssh.exe -F "#{WTMPDW}\\config" -oAddKeysToAgent=yes #{dest}
							END
							puts `wslpath -w #{proxyBat}`.chomp
							STDOUT.flush
						else
							sshWithVerbose = ["ssh"]
							optLine.count("-v").times do
								sshWithVerbose << "-v"
							end
							cline = [*sshWithVerbose, "-R#{free_port}:127.0.0.1:#{vport}", "-oExitOnForwardFailure=yes", "-oAddKeysToAgent=yes", *ARGV, "-t", "/tmp/vscode_control/shell_wrappers/#{rand_id}.ssha_set_vsc_port.sh"]
							do_ssh *cline
						end
					else
						STDERR.puts "ERROR: cannot find VSCode Control Server port."
						exit 1
					end
				else
					# cmdarrの前に標準出力に乱数を書き出すコマンドを追加、ローカルでこの乱数を検出することで、接続の成功を確認してconfigに登録する
					case SSH_ORG
					when "ssh"
						cmdline = [SSH_ORG, *ARGV]
						if print_tmp_script_file_name && BY_SSH_BAT
							proxyScript = "#{WTMPDL}/ssh_proxy.sh"
							IO.write proxyScript, <<~END
								#!/bin/bash
								#{cmdline.shelljoin}    
							END
							puts proxyScript
							STDOUT.flush
						else
							exec SSH_ORG, "-oAddKeysToAgent=yes", *ARGV
						end
					when "ssh.exe"
						proxyBat = "#{WTMPDL}/ssh_proxy.bat"
						begin
							IO.write proxyBat, <<~END
								@echo off
								set SSH_ASKPASS=c:\\Program Files\\Git\\mingw64\\bin\\git-askpass.exe
								set SSH_ASKPASS_REQUIRE=force
								ssh.exe -F "#{WTMPDW}\\config" -oAddKeysToAgent=yes #{dest} #{cmdarr.map{ |e| e.include?(" ") ? "\"#{e}\"" : e }.join(" ")}
							END
							if print_tmp_script_file_name
								puts `wslpath -w #{proxyBat}`.chomp
								STDOUT.flush
							else
								exec "/mnt/c/Program Files/Git/usr/bin/winpty.exe", "-Xallow-non-tty", `wslpath -w #{proxyBat}`.chomp
							end
						ensure
							#FileUtils.rm_f proxyBat
						end
					end
				end
			end
		end
	end
	return
end


main

